[package]
name = "monitorctl-core"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "monitorctl"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.9"
windows = { version = "0.62.2", features = [
    "Win32_Devices_Display",
    "Win32_Foundation",
] }
